name: Generate ASCII Art Workflow
on: 
    workflow_dispatch:
#   schedule:
#     - cron: '* * * * 0'  # Runs weekly on Sundays at midnight
env:
    GLOBAL_ART_STYLE: "dragon"
jobs:
    generate_ascii_art:
        env:
            ARTIST_NAME: "DragonMaster"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install cowsay program and Generate ASCII Art
              run: |
                   sudo apt-get update
                   sudo apt-get install -y cowsay
                   echo "Hello from $ARTIST_NAME using style $GLOBAL_ART_STYLE"
                   echo "Generating ASCII Art..."
                   cowsay -f dragon "I am a dragon!" >> dragon_art.txt
                   grep "dragon" dragon_art.txt

            - name: Executing Shell Script
              run: |
                     chmod +x ./shell.sh
                     ./shell.sh

            - name: Upload Generated ASCII Art
              uses: actions/upload-artifact@v4
              with:
                  name: dragon-art
                  path: dragon_art.txt

    read_ascii_art:
        runs-on: ubuntu-latest
        needs: generate_ascii_art
        steps:
            - name: Download Generated ASCII Art
              uses: actions/download-artifact@v5
              with:
                  name: dragon-art

            - name: Read Generated ASCII Art
              run: |
                   echo "Reading Generated ASCII Art..."
                   cat dragon_art.txt


# to access repository secrets in a workflow, use the syntax ${{ secrets.SECRET_NAME }}
# to access repository variables in a workflow, use the syntax ${{ vars.VARIABLE_NAME }}