name: Matrix Strategy
on:
    workflow_dispatch:
jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest]
                images: [hello-world, alpine]
                exclude:
                    - os: windows-latest
                      images: alpine
        runs-on: ${{ matrix.os }}
        steps:

            - name: Echo docker details
              run: |
                     echo "Running on OS: ${{ matrix.os }}"
                     echo "matrix context : ${{ toJson(matrix) }}"
                     docker info
            - name: Run Image on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}
              