name: Matrix Strategy
on:
    workflow_dispatch:
    push:
        branches-ignore:
            - docs/**
    pull_request:
        types: [opened, synchronize, reopened, edited, ready_for_review, reopened]
        paths-ignore:
            - docs/**
            - README.md
        branches:
            - main
jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest]
                images: [hello-world, alpine]
                exclude:
                    - os: windows-latest
                      images: alpine
        runs-on: ${{ matrix.os }}
        steps:
            - name: Echo docker details
              if: matrix.images == 'alpine' && matrix.os == 'ubuntu-latest'
              run: |
                     echo "Running on OS: ${{ matrix.os }}"
                     echo "matrix context : ${{ toJson(matrix) }}"
                     echo "Running on event : ${{ toJson(github.event_name) }}"
                     docker info
            - name: Run Image on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}
              
# to skip workflow execution for a commit, include [skip ci] or [ci skip] in the commit message